algoritmo "Estrutura repita"
// Função :
// Autor :
// Data : 27/04/2020
// Seção de Declarações 
var
    sairloop : caractere
    valor01, valor02: real
inicio
// Seção de Comandos 
    repita
         Escreva ("Digite o primeiro valor: ")
         leia (valor01)
         Escreva ("Digite o segundo valor: ")
         leia (valor02)
         Escreval ("Resultado: ", valor01 + valor02)
         Escreval ("Deseja sair?  S/N")
         leia (sairloop)
    ate sairloop <> "N"


fimalgoritmo
