algoritmo "estrutura-para-faca"
// Função :
// Autor :
// Data : 27/04/2020
// Seção de Declarações
var
    numero, fatorial, contador: inteiro
inicio
// Seção de Comandos
   escreva ("Digite o numero para calcular o fatorial: ")
   leia (numero)
   fatorial :=1
   para contador de 1 ate numero faca
        fatorial := fatorial * contador
   fimpara
   escreval ("O fatorial de", numero, " é: ", fatorial)



fimalgoritmo
